### ISSUE TITLE
The 'daily_flutter_audio_manager_events' channel sent a message from native to Flutter on a non-platform thread.

### ISSUE THREAD

**Issue by chingiz** [VapiAI/flutter#4]
Hi,

I'm getting this error, any help?

```
[ERROR:flutter/shell/common/shell.cc(1038)] The 'daily_flutter_audio_manager_events' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
```

After this app crashes.

**Comment by chingiz** [comment]
Note: I'm using example in [https://github.com/VapiAI/flutter/tree/main/example]( https://github.com/VapiAI/flutter/tree/main/example)

**Comment by chingiz** [comment]
@nikhilro ?

**Comment by jordancde** [comment]
Looks like we have been able to reproduce the issue. I believe this issue has started with Flutter 3.13, which has stricter detection of multi-threading. However, everything continues to work despite the fact that this message is appearing.
It is going to be fixed in our next Flutter release, which should happen either later this week or early next week.

**Comment by FaezAnsar** [comment]
Did you solve it? i'm using VAPI Ai and have also upgraded flutter but still same issue

**Comment by chingiz** [comment]
Upgrade vapi sdk to latest. It's resolved already.
